🔀 :: (#42) 클럽장 변경 API
DMSport/DMSport-Server pull request #43
Opened 2022-10-07 07:30 UTC by alsdl0629

### 해당 이슈⚡️

- close #42 

### 변경사항✅

- 클럽장 변경 API

2022-10-07 10:16 UTC, tedsoftj1123 requested changes

2022-10-07 10:16 UTC, tedsoftj1123 commented on src/main/java/com/project/dmsport/domain/admin/service/ChangeClubManagerService.java
> +                .orElseThrow(() -> ClubManagerNotFoundException.EXCEPTION);
요 findbyid도 퍼사드에 넣는건 어떠한지

2022-10-07 10:16 UTC, tedsoftj1123 commented on src/main/java/com/project/dmsport/domain/admin/service/ClubBanService.java
>                  .ban(club.isBan())
이거 인자 하나면 그냥 빌더 쓰지말고 생성자로 하셈

2022-10-07 10:16 UTC, tedsoftj1123 commented on src/main/java/com/project/dmsport/domain/admin/service/ClubBanService.java
> +    private final ClubFacade clubFacade;
생성자 어디감

2022-10-07 10:16 UTC, tedsoftj1123 commented on src/main/java/com/project/dmsport/domain/club/facade/ClubFacade.java
> +}
요 로직은 상의 해보는걸로

2022-10-08 02:38 UTC, rlaisqls commented on src/main/java/com/project/dmsport/domain/club/facade/ClubFacade.java
> +}
왜 상의해야해..?

2022-10-08 10:59 UTC, tedsoftj1123 commented on src/main/java/com/project/dmsport/domain/club/facade/ClubFacade.java
> +}
어.. 뭐 다른 방법있어서 따로 얘기 해봐야되는줄 알았는데 잘못 아해한듯

2022-10-08 11:00 UTC, tedsoftj1123 approved these changes

2022-10-08 11:02 UTC, merged

2022-10-09 04:36 UTC, rlaisqls commented on src/main/java/com/project/dmsport/domain/user/domain/User.java
> +
이거 로직이 너무 헷갈리는데 이 메서드에는 그냥 
`this.authority = authority`로만 놓고
메서드에서 두 유저 정보를 각각 수정하도록 하는게 나을 것 같아

2022-10-09 04:36 UTC, rlaisqls commented on src/main/java/com/project/dmsport/domain/admin/service/ChangeClubManagerService.java
> +        clubManager.getUser().changeUserAuthority(user, authority);
이거 
`User oldManagerUser = clubManager.getUser()`
로 변수 한번 거쳐서 해주는게 가독성에 더 좋을 것 같아
위에 request로 id 받아서 조회하는 유저 변수 이름도 `newManagerUser` 로 해주면 더더 좋을듯

2022-10-09 04:36 UTC, rlaisqls commented on src/main/java/com/project/dmsport/domain/admin/service/QueryUserListService.java
> +                .collect(Collectors.toList());
이거 네가 짠거 아닌거 알지만.. 바꾼김에
```java
        return userRepository.findAllOrderByIdDesc()
                .stream()
                .map(user -> UserListResponse.builder()
                                .id(user.getId())
                                .name(user.getName())
                                .authority(user.getAuthority())
                                .build())
                .collect(Collections.toList());
```
이렇게 바꿔줄 수 있어?

2022-10-09 04:36 UTC, rlaisqls commented on src/main/java/com/project/dmsport/domain/admin/service/ClubBanService.java
> +    private final ClubFacade clubFacade;
꼭 추가해야할듯
우리 풀리퀘 전에 한번 애플리케이션 돌려보고 올리자