🔀 :: (#77)최근공지 조회
DMSport/DMSport-Server pull request #88
Opened 2022-11-09 14:11 UTC by tedsoftj1123

### 해당 이슈⚡️

-close #77

### 변경사항✅

- 최근공지 기능 추가 map사용
- 조회된 타입인 Notice에서 반환할 타입인 NoticeType을로 바꾸는 코드를
  facade로 묶었습니다.
- 그 따로 @OrderBy어노테이션 사용할려 했는데 검색해보니까 보통 엔티티 컬럼에 쓰는거같은데
  아무리 해봐도 적용이 되질 않아서 일단 NoticeRepository에 달아놨습니다.
- 접근 권한설정

2022-11-09 23:31 UTC, rlaisqls requested changes

2022-11-09 23:31 UTC, rlaisqls commented on src/main/java/com/project/dmsport/domain/notice/facade/NoticeFacade.java
> +    }
다른 빈(컴포넌트)에 의존하지 않는 코드는 Facade에 넣지 말고 객체 내부 메서드로 넣는게 좋을 것 같습니다. 그래야 코드의 응집도를 높일 수 있으니까요.
noticeToNoticeResponse는 NoriceResopnse의 static of메서드로, generateContent는 Notice의 static 메서드로 넣는거 어떨까요?

2022-11-09 23:31 UTC, rlaisqls commented on src/main/java/com/project/dmsport/domain/notice/service/QueryAllNoticesService.java
> +                noticeFacade.noticeToNoticeResponse(noticeRepository.findAllByOrderByCreatedDateDesc()));
여기선 List<NoticeResponse>를 만들때 그냥 map을 살리고, Notice를 NoticeResponse로 바꾸는 메서드 사용하는게 더 나을 것 같아요.

stream map을 쓰는 코드가 공지 조회 부분에서 중복되어 나타나는건 맞지만, 그래도 서비스 로직에서 로직의 대략적인 흐름은 알 수 있게 해야하니까요! (그리고 noticeToNotice라는 메서드명이 List를 반환한다는 느낌이 안나기는 해요. 그치만 그냥 map이 드러나게 짜는게 더 깔끔할 것 같아요.)

2022-11-09 23:31 UTC, rlaisqls commented on src/main/java/com/project/dmsport/domain/notice/service/QueryRecentNoticeService.java
> +                noticeRepository.findTop2ByNoticeTypeNotOrderByCreatedDateDesc(NoticeType.ALL));
이거 왜 둘다 NoticeType.ALL인가요?
(그리고 얘도 그냥 map으로 풀어쓰는게 나을 것 같아요)

2022-11-09 23:31 UTC, rlaisqls commented on src/main/java/com/project/dmsport/global/security/SecurityConfig.java
> +                .anyRequest().permitAll()
원래 로그인, 회원가입 비밀번호갖기 등의 기능을 제외한 나머지의 기능(ex 투표하기, 공지 조회 등)은 무조건 로그인 한 후에 사용해야하는 기능이기 때문에 꼭 토큰 같이 보내도록 하기 위해서 `authenticated()`로 해놨었는데 왜 `permitAll()`로 바꾸셨나요?

2022-11-09 23:35 UTC, rlaisqls commented on src/main/java/com/project/dmsport/domain/notice/service/QueryRecentNoticeService.java
> +                noticeRepository.findTop2ByNoticeTypeNotOrderByCreatedDateDesc(NoticeType.ALL));
이거 변수명 `adminNoticeList`로 쓰는건 어떨까요?
admin, manager여도 구분은 확실히 할 수 있지만 약간 혼동될 여지가 있는 것 같아요

2022-11-09 23:41 UTC, tedsoftj1123 commented on src/main/java/com/project/dmsport/domain/notice/service/QueryRecentNoticeService.java
> +                noticeRepository.findTop2ByNoticeTypeNotOrderByCreatedDateDesc(NoticeType.ALL));
admin에 사용된 메소드는 noticetype이 all인걸 찾는메소드이고
manager에 사용된 메소드는 noticetype이 all이지 않은것만 조회해서 top2찾는 메소드입니다.(스클공지들)
`findTop2ByNoticeTypeNot`

2022-11-09 23:42 UTC, tedsoftj1123 commented on src/main/java/com/project/dmsport/global/security/SecurityConfig.java
> +                .anyRequest().permitAll()
테스트 할려고 바꿨다가 그냥 올려버렸네요 수정하겠습니다.

2022-11-10 00:38 UTC, tedsoftj1123 commented on src/main/java/com/project/dmsport/domain/notice/facade/NoticeFacade.java
> +    }
noticeresponse변환 메소드는 따로 스태틱으로 만들었고 generateContent같은 경우 앞의 변환 메소드에서
인자로 받고 있어서 일반 메소드로 추가 했습니다.

2022-11-10 01:41 UTC, rlaisqls commented on src/main/java/com/project/dmsport/domain/notice/service/QueryRecentNoticeService.java
> +                noticeRepository.findTop2ByNoticeTypeNotOrderByCreatedDateDesc(NoticeType.ALL));
아하

2022-11-10 01:43 UTC, rlaisqls approved these changes

2022-11-10 03:11 UTC, alsdl0629 approved these changes

2022-11-10 03:11 UTC, alsdl0629 commented on src/main/java/com/project/dmsport/global/security/SecurityConfig.java
> +                .anyRequest().permitAll()
p1 이게 맞나요

2022-11-10 03:31 UTC, merged